AllCops:
  TargetRubyVersion: 2.1

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/IndentAssignment:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false
